Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g31, pull requests merged in 2024-09, with the labels that each got.

#3 Setup Frontend
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/app/favicon.ico
  frontend/app/fonts/GeistMonoVF.woff
  frontend/app/fonts/GeistVF.woff
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/components.json
  frontend/lib/utils.ts
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/postcss.config.mjs
  frontend/tailwind.config.js
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: enhancement

#17 [#6] Setup user service project
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc
  backend/user-service/__tests__/index.test.ts
  backend/user-service/jest.config.js
  backend/user-service/package-lock.json
  backend/user-service/package.json
  backend/user-service/src/index.ts
  backend/user-service/src/server.ts
  backend/user-service/src/types/ResponseError.ts
  backend/user-service/tsconfig.json
  eslint.config.mjs
  package-lock.json
  package.json
Labels: enhancement

#24 [#7] Add user data model
  .gitignore
  backend/user-service/__tests__/index.test.ts
  backend/user-service/__tests__/models/user.repository.test.ts
  backend/user-service/package-lock.json
  backend/user-service/package.json
  backend/user-service/src/common/logger.util.ts
  backend/user-service/src/common/mongodb.util.ts
  backend/user-service/src/index.ts
  backend/user-service/src/models/user.model.ts
  backend/user-service/src/models/user.repository.ts
  backend/user-service/src/server.ts
  backend/user-service/src/types/CreateUserDto.ts
  backend/user-service/src/types/IUser.ts
  backend/user-service/src/types/Proficiency.ts
  backend/user-service/src/types/ResponseError.ts
  backend/user-service/src/types/Role.ts
  backend/user-service/src/types/TypedRequest.ts
  backend/user-service/src/types/UserDto.ts
  backend/user-service/tsconfig.json
  package-lock.json
Labels: enhancement

#26 Add POST API for user creation
  backend/user-service/__tests__/models/user.repository.test.ts
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/package-lock.json
  backend/user-service/package.json
  backend/user-service/src/controllers/auth.controller.ts
  backend/user-service/src/controllers/user.controller.ts
  backend/user-service/src/index.ts
  backend/user-service/src/routes/user.routes.ts
  backend/user-service/src/types/CreateUserDto.ts
  package-lock.json
Labels: enhancement

#28 feat: add update profile api route
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/src/controllers/user.controller.ts
  backend/user-service/src/models/user.repository.ts
  backend/user-service/src/routes/user.routes.ts
  backend/user-service/src/types/UserProfileDto.ts
Labels: enhancement

#27 feat: create dashboard page
  eslint.config.mjs
  frontend/.eslintrc.json
  frontend/__tests__/page.test.tsx
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/components.json
  frontend/components/dashboard/new-session.tsx
  frontend/components/dashboard/progress-card.tsx
  frontend/components/dashboard/recent-sessions.tsx
  frontend/components/navbar.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/navigation-menu.tsx
  frontend/components/ui/progress.tsx
  frontend/components/ui/select.tsx
  frontend/components/ui/table.tsx
  frontend/components/ui/typography.tsx
  frontend/lib/utils.ts
  frontend/next.config.mjs
  frontend/package.json
  frontend/postcss.config.js
  frontend/postcss.config.mjs
  frontend/public/logo.svg
  frontend/tailwind.config.js
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  package-lock.json
Labels: enhancement

#41 Implement authentication API
  backend/user-service/__tests__/index.test.ts
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/package-lock.json
  backend/user-service/package.json
  backend/user-service/src/common/config.util.ts
  backend/user-service/src/controllers/auth.controller.ts
  backend/user-service/src/index.ts
  backend/user-service/src/routes/auth.routes.ts
  backend/user-service/src/server.ts
  backend/user-service/src/types/Config.ts
  backend/user-service/src/types/IAccessTokenPayload.ts
  package-lock.json
Labels: enhancement

#45 Setup question service project and dependencies
  backend/question-service/__tests__/index.test.ts
  backend/question-service/__tests__/routes/question.routes.test.ts
  backend/question-service/jest.config.js
  backend/question-service/package-lock.json
  backend/question-service/package.json
  backend/question-service/src/common/config.util.ts
  backend/question-service/src/common/logger.util.ts
  backend/question-service/src/common/mongodb.util.ts
  backend/question-service/src/index.ts
  backend/question-service/src/routes/question.routes.ts
  backend/question-service/src/server.ts
  backend/question-service/src/types/Config.ts
  backend/question-service/tsconfig.json
  package-lock.json
Labels: enhancement

#46 Set up page routing and base layout
  frontend/__tests__/page.test.tsx
  frontend/app/fonts/GeistMonoVF.woff
  frontend/app/fonts/GeistVF.woff
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/components/layout/layout.tsx
  frontend/components/layout/navbar.tsx
  frontend/jest.config.ts
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/styles/fonts.ts
  frontend/styles/globals.css
  frontend/tsconfig.json
Labels: enhancement

#48 Fix async error handling
  backend/question-service/__tests__/routes/question.routes.test.ts
  backend/question-service/package-lock.json
  backend/question-service/src/index.ts
  backend/question-service/src/middlewares/errorHandler.middleware.ts
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/package-lock.json
  backend/user-service/package.json
  backend/user-service/src/controllers/user.controller.ts
  backend/user-service/src/index.ts
  backend/user-service/src/middlewares/errorHandler.middleware.ts
  eslint.config.mjs
  package-lock.json
Labels: bug

#47 Setup DELETE API for Hard Deletion of User
  CODEOWNERS
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/src/controllers/user.controller.ts
  backend/user-service/src/routes/user.routes.ts
Labels: enhancement

#50 Make minor UI fixes
  frontend/components/layout/layout.tsx
  frontend/components/layout/navbar.tsx
  frontend/styles/globals.css
Labels: bug, enhancement

#51 Implement question data schema and model
  backend/question-service/__mocks__/question.mock.ts
  backend/question-service/__tests__/routes/question.routes.test.ts
  backend/question-service/src/common/mongodb.util.ts
  backend/question-service/src/models/question.model.ts
  backend/question-service/src/models/question.repository.ts
  backend/question-service/src/types/Complexity.ts
  backend/question-service/src/types/CreateQuestionDto.ts
  backend/question-service/src/types/IQuestion.ts
  backend/question-service/src/types/TypedRequest.ts
Labels: enhancement

#58 Implement Password Reset/Update Functionality
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/package.json
  backend/user-service/public/passwordResetEmail.html
  backend/user-service/src/controllers/auth.controller.ts
  backend/user-service/src/controllers/user.controller.ts
  backend/user-service/src/index.ts
  backend/user-service/src/models/user.model.ts
  backend/user-service/src/models/user.repository.ts
  backend/user-service/src/routes/auth.routes.ts
  backend/user-service/src/routes/user.routes.ts
  backend/user-service/src/types/Config.ts
  backend/user-service/src/types/EmailVerificationDto.ts
  backend/user-service/src/types/IUser.ts
  backend/user-service/src/types/UserPasswordDto.ts
  backend/user-service/tsconfig.json
  frontend/components/auth/Login.tsx
  frontend/components/auth/PasswordReset.tsx
  frontend/components/auth/Signup.tsx
  frontend/components/dashboard/new-session.tsx
  frontend/components/login/ui/toast/Logo.tsx
  frontend/components/ui/dialog.tsx
  frontend/components/ui/input-otp.tsx
  frontend/components/ui/toast.tsx
  frontend/components/ui/toaster.tsx
  frontend/components/ui/use-toast.tsx
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/auth/index.tsx
  package-lock.json
Labels: enhancement

#59 [#14] Create jwt authorisation middleware with access control
  backend/question-service/jest.config.js
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/jest.config.js
  backend/user-service/package-lock.json
  backend/user-service/package.json
  backend/user-service/src/common/mail.util.ts
  backend/user-service/src/common/mongodb.util.ts
  backend/user-service/src/common/password.util.ts
  backend/user-service/src/common/template.util.ts
  backend/user-service/src/common/token.util.ts
  backend/user-service/src/controllers/auth.controller.ts
  backend/user-service/src/controllers/user.controller.ts
  backend/user-service/src/index.ts
  backend/user-service/src/middlewares/accessControl.middleware.ts
  backend/user-service/src/middlewares/passportJwt.middleware.ts
  backend/user-service/src/middlewares/passportLocal.middleware.ts
  backend/user-service/src/models/user.model.ts
  backend/user-service/src/models/user.repository.ts
  backend/user-service/src/routes/auth.routes.ts
  backend/user-service/src/routes/user.routes.ts
  backend/user-service/src/types/IUser.ts
  backend/user-service/src/types/UserProfileDto.ts
  frontend/package-lock.json
  package-lock.json
Labels: enhancement

#62 Implement UI for collaborative coding page
  frontend/assets/icons/csharp.jsx
  frontend/assets/icons/end.jsx
  frontend/assets/icons/golang.jsx
  frontend/assets/icons/index.tsx
  frontend/assets/icons/java.jsx
  frontend/assets/icons/javascript.jsx
  frontend/assets/icons/play.jsx
  frontend/assets/icons/python.jsx
  frontend/assets/icons/ruby.jsx
  frontend/assets/icons/submit.jsx
  frontend/assets/icons/typescript.jsx
  frontend/components/customs/custom-tabs.tsx
  frontend/components/customs/difficulty-label.tsx
  frontend/components/layout/layout.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/label.tsx
  frontend/mock-data/index.ts
  frontend/package.json
  frontend/pages/code/index.tsx
  frontend/pages/code/language-mode-select.tsx
  frontend/pages/code/testcase-tab.tsx
  frontend/public/icons/alert-triangle.svg
  frontend/public/icons/alert.svg
  frontend/public/icons/cross.svg
  frontend/public/icons/fail.svg
  frontend/public/icons/left-arrow.svg
  frontend/public/icons/maximise.svg
  frontend/public/icons/minimise.svg
  frontend/public/icons/selected-tick.svg
  frontend/styles/globals.css
  frontend/tailwind.config.js
  frontend/types/difficulty.ts
  frontend/types/index.ts
  frontend/types/language-mode.ts
  frontend/types/question.ts
  frontend/types/test-case.ts
  package-lock.json
Labels: enhancement

#65 34 35 be question service implement put delete apis for updating and deleting questions
  backend/question-service/__tests__/routes/question.routes.test.ts
  backend/question-service/src/controllers/question.controller.ts
  backend/question-service/src/models/question.model.ts
  backend/question-service/src/models/question.repository.ts
  backend/question-service/src/routes/question.routes.ts
  backend/question-service/src/types/IPaginationRequest.ts
  backend/question-service/src/types/QuestionDto.ts
  backend/user-service/__tests__/routes/user.routes.test.ts
  backend/user-service/package-lock.json
  backend/user-service/package.json
  backend/user-service/src/controllers/user.controller.ts
  frontend/package-lock.json
  package-lock.json
  package.json
Labels: enhancement

#63 Questions page
  frontend/assets/icons/close.tsx
  frontend/assets/icons/cross.tsx
  frontend/assets/icons/delete.tsx
  frontend/assets/icons/edit.tsx
  frontend/assets/icons/exclamation.tsx
  frontend/assets/icons/index.tsx
  frontend/assets/icons/left.tsx
  frontend/assets/icons/right.tsx
  frontend/assets/icons/tick.tsx
  frontend/assets/icons/warning.tsx
  frontend/components/customs/custom-form.tsx
  frontend/components/customs/custom-modal.tsx
  frontend/components/customs/custom-select.tsx
  frontend/components/customs/datatable.tsx
  frontend/components/customs/multiple-select.tsx
  frontend/components/customs/sort-icon.tsx
  frontend/components/ui/badge.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/difficult-badge.tsx
  frontend/components/ui/label.tsx
  frontend/components/ui/select.tsx
  frontend/components/ui/table.tsx
  frontend/mock-data/index.ts
  frontend/package.json
  frontend/pages/questions/index.tsx
  frontend/pages/questions/props.tsx
  frontend/pages/sessions/index.tsx
  frontend/types/datatable.ts
  frontend/types/difficulty.ts
  frontend/types/form.ts
  frontend/types/index.ts
  frontend/types/question.ts
  package-lock.json
Labels: enhancement

#74 [#73] add apis to get filters and sorts for pagination
  backend/question-service/__tests__/routes/question.routes.test.ts
  backend/question-service/src/controllers/question.controller.ts
  backend/question-service/src/models/question.repository.ts
  backend/question-service/src/routes/question.routes.ts
  backend/question-service/src/types/QuestionDto.ts
Labels: enhancement
